### ISSUE TITLE
Training loss is always zero in Stage 2. 

### ISSUE THREAD

**Issue by LiWentomng** [jshilong/GPT4RoI#25]
Hello, in my  training process of stage 2, the loss is always zero, like the below figure.  Is it normal?

![loss](https://github.com/jshilong/GPT4RoI/assets/32033843/d8147123-9578-47f1-b219-a724501afa0d)

**Comment by jshilong** [comment]
This usually occurs when you fail to load weights or load the incorrect weights. 
To debug this issue, please use the merged wegith https://huggingface.co/shilongz/debug/tree/main
 which can help verify if your weight conversion is correct.

**Comment by jshilong** [comment]
@LiWentomng Have you solved the problem?

**Comment by LiWentomng** [comment]
Thanks for your answer.  When using the model of your `debug` weights, the loss is normal.   I try to find the problem in my weights.

**Comment by LiWentomng** [comment]
@jshilong 
I encounter another problem. When I use 4 gpus, the training process is well-processed. When I use 8 gpus, the error will occure like below for both stage1 and stage2.

```
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122458 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122459 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122460 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122461 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122463 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122464 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 5 (pid: 122462) of binary: /workspace/conda_env/gpt4roi/bin/python
Traceback (most recent call last):
  File "/workspace/conda_env/gpt4roi/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/workspace/conda_env/gpt4roi/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/workspace/conda_env/gpt4roi/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/workspace/conda_env/gpt4roi/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/workspace/conda_env/gpt4roi/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/workspace/conda_env/gpt4roi/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=======================================================
gpt4roi/train/train_mem.py FAILED
-------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-27_13:31:58
  host      : transrisk-kmaker-033148052140
  rank      : 5 (local_rank: 5)
  exitcode  : -9 (pid: 122462)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 122462
```
Have you encountered this problem?

**Comment by Anonymous-Researcher1** [comment]
> @jshilong I encounter another problem. When I use 4 gpus, the training process is well-processed. When I use 8 gpus, the error will occure like below for both stage1 and stage2.
> 
> ```
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122458 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122459 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122460 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122461 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122463 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122464 closing signal SIGTERM
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 5 (pid: 122462) of binary: /workspace/conda_env/gpt4roi/bin/python
> Traceback (most recent call last):
>   File "/workspace/conda_env/gpt4roi/bin/torchrun", line 8, in <module>
>     sys.exit(main())
>   File "/workspace/conda_env/gpt4roi/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
>     return f(*args, **kwargs)
>   File "/workspace/conda_env/gpt4roi/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
>     run(args)
>   File "/workspace/conda_env/gpt4roi/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
>     elastic_launch(
>   File "/workspace/conda_env/gpt4roi/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/workspace/conda_env/gpt4roi/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> =======================================================
> gpt4roi/train/train_mem.py FAILED
> -------------------------------------------------------
> Failures:
>   <NO_OTHER_FAILURES>
> -------------------------------------------------------
> Root Cause (first observed failure):
> [0]:
>   time      : 2023-09-27_13:31:58
>   host      : transrisk-kmaker-033148052140
>   rank      : 5 (local_rank: 5)
>   exitcode  : -9 (pid: 122462)
>   error_file: <N/A>
>   traceback : Signal 9 (SIGKILL) received by PID 122462
> ```
> 
> Have you encountered this problem?

Sure, I've encountered this issue before. It happens when there is insufficient memory to load the model(too many processes load the model to memory at the same time).

**Comment by jshilong** [comment]
> @jshilong I encounter another problem. When I use 4 gpus, the training process is well-processed. When I use 8 gpus, the error will occure like below for both stage1 and stage2.
> 
> ```
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122458 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122459 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122460 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122461 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122463 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122464 closing signal SIGTERM
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 5 (pid: 122462) of binary: /workspace/conda_env/gpt4roi/bin/python
> Traceback (most recent call last):
>   File "/workspace/conda_env/gpt4roi/bin/torchrun", line 8, in <module>
>     sys.exit(main())
>   File "/workspace/conda_env/gpt4roi/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
>     return f(*args, **kwargs)
>   File "/workspace/conda_env/gpt4roi/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
>     run(args)
>   File "/workspace/conda_env/gpt4roi/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
>     elastic_launch(
>   File "/workspace/conda_env/gpt4roi/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/workspace/conda_env/gpt4roi/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> =======================================================
> gpt4roi/train/train_mem.py FAILED
> -------------------------------------------------------
> Failures:
>   <NO_OTHER_FAILURES>
> -------------------------------------------------------
> Root Cause (first observed failure):
> [0]:
>   time      : 2023-09-27_13:31:58
>   host      : transrisk-kmaker-033148052140
>   rank      : 5 (local_rank: 5)
>   exitcode  : -9 (pid: 122462)
>   error_file: <N/A>
>   traceback : Signal 9 (SIGKILL) received by PID 122462
> ```
> 
> Have you encountered this problem?

> @jshilong I encounter another problem. When I use 4 gpus, the training process is well-processed. When I use 8 gpus, the error will occure like below for both stage1 and stage2.
> 
> ```
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122458 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122459 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122460 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122461 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122463 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122464 closing signal SIGTERM
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 5 (pid: 122462) of binary: /workspace/conda_env/gpt4roi/bin/python
> Traceback (most recent call last):
>   File "/workspace/conda_env/gpt4roi/bin/torchrun", line 8, in <module>
>     sys.exit(main())
>   File "/workspace/conda_env/gpt4roi/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
>     return f(*args, **kwargs)
>   File "/workspace/conda_env/gpt4roi/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
>     run(args)
>   File "/workspace/conda_env/gpt4roi/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
>     elastic_launch(
>   File "/workspace/conda_env/gpt4roi/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/workspace/conda_env/gpt4roi/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> =======================================================
> gpt4roi/train/train_mem.py FAILED
> -------------------------------------------------------
> Failures:
>   <NO_OTHER_FAILURES>
> -------------------------------------------------------
> Root Cause (first observed failure):
> [0]:
>   time      : 2023-09-27_13:31:58
>   host      : transrisk-kmaker-033148052140
>   rank      : 5 (local_rank: 5)
>   exitcode  : -9 (pid: 122462)
>   error_file: <N/A>
>   traceback : Signal 9 (SIGKILL) received by PID 122462
> ```
> 
> Have you encountered this problem?

Sure, I've encountered this issue before. It happens when there is insufficient memory to load the model(too many processes load the model to memory at the same time).

**Comment by LiWentomng** [comment]
@jshilong  
Thanks for your help. My problem is solved, and  my  weight of stage 1  is something wrong. I retrained the stage1 and merged the weights. The  training processing of stage 2 is normal.

Besides, looking forward to the quantitative evalution  and the updated paper~
